stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ./fluentd-aggregator/latest
      catalog: fluentd
      version: latest
      gitUrl: git@github.com:rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: test
      gitEmail: test@rancher.com
    envFrom:
    - sourceName: deploy-key
      sourceKey: DEPLOY_KEY
      targetKey: DEPLOY_KEY
- name: deploy
  steps:
  - applyAppConfig:
      catalog: library
      version: 3.0.2
      name: library-redis
      targetNamespace: default
timeout: 60
notification: {}
