stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ./mongodb/v2.0.2
      catalog: mongodb
      version: v2.0.2
      gitUrl: https://github.com/rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: rootwuj
      gitEmail: jing@rancher.com
    envFrom:
    - sourceName: s-9dz92
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: s-9dz92
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
