stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ./efk/v0.1.2
      catalog: efk
      version: v0.1.2
      gitUrl: https://github.com/rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: aaa
      gitEmail: aaa@qq.com
    env:
      elasticsearch.master.persistence.storageClass: nsfaaa
    envFrom:
    - sourceName: mima
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: mima
      sourceKey: PASSWORD
      targetKey: PASSWORD
    when:
      branch: {}
- name: publish2
  steps:
  - publishCatalogConfig:
      path: ./efk/v0.1.3
      catalog: efk
      version: v0.1.3
      gitUrl: git@github.com:rancher/rancher.git
      gitBranch: master
      gitAuthor: bb
      gitEmail: bb@rancher.com
    envFrom:
    - sourceName: key
      sourceKey: DEPLOY_KEY
      targetKey: DEPLOY_KEY
timeout: 60
notification: {}
