stages:
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mariadb
      version: 3.0.3
      name: MariaDB-aa
      targetNamespace: default
timeout: 60
notification: {}
