stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ./mongodb/latest
      catalogTemplate: mongo
      version: latest
      gitUrl: https://github.com/rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: wujing
      gitEmail: jing@rancher.com
    envFrom:
    - sourceName: password
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: password
      sourceKey: PASSWORD
      targetKey: PASSWORD
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: library-mysql
      version: 0.3.7
      name: mymkmy
      targetNamespace: default
timeout: 60
notification: {}
