stages:
- name: deploy
  steps:
  - publishCatalogConfig:
      path: ./mongodb/latest
      catalogTemplate: mongo
      version: latest
      gitUrl: git@github.com:rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: wujing
      gitEmail: jing@rancher.com
    envFrom:
    - sourceName: key
      sourceKey: DEPLOY_KEY
      targetKey: DEPLOY_KEY
timeout: 60
notification: {}
