stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ./efk/v0.1.2
      catalog: efk
      version: v0.1.2
      gitUrl: https://github.com/rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: aaa
      gitEmail: aaa@qq.com
    envFrom:
    - sourceName: mima
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: mima
      sourceKey: PASSWORD
      targetKey: PASSWORD
    when:
      branch:
        include:
        - v1
- name: publish2
  steps:
  - publishCatalogConfig:
      path: ./efk/v0.1.3
      catalog: efk
      version: v0.1.3
      gitUrl: https://github.com/rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: bb
      gitEmail: bb@rancher.com
    envFrom:
    - sourceName: mima
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: mima
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
