stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ./fluentd-aggregator/latest
      catalog: fluentd
      version: latest
      gitUrl: git@github.com:rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: test
      gitEmail: test@rancher.com
    envFrom:
    - sourceName: key
      sourceKey: DEPLOY_KEY
      targetKey: DEPLOY_KEY
timeout: 60
notification: {}
