stages:
- name: 部署
  steps:
  - publishCatalogConfig:
      path: ./fluentd-aggregator/latest
      catalog: fluentd-wuj
      version: latest
      gitUrl: git@github.com:rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: ddff
      gitEmail: ddff@qq.com
    envFrom:
    - sourceName: "288"
      sourceKey: DEPLOY_KEY
      targetKey: DEPLOY_KEY
timeout: 60
notification: {}
