stages:
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mariadb
      version: 5.0.9
      answers:
        db.name: my_database
        db.password: admin
        db.user: admin
        defaultImage: "true"
        image.repository: bitnami/mariadb
        image.tag: 10.1.36-debian-9
        master.persistence.enabled: "false"
        master.persistence.size: 8Gi
        metrics.enabled: "false"
        metrics.image: prom/mysqld-exporter
        metrics.imageTag: v0.10.0
        replication.enabled: "true"
        service.type: NodePort
        slave.persistence.enabled: "false"
        slave.persistence.size: 8Gi
        slave.replicas: "2"
      name: MariaDB-aa
      targetNamespace: default
timeout: 60
notification: {}
