stages:
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mariadb
      version: 5.0.9
      answers:
        db.name: my_database
        db.password: admin
        db.user: admin
        defaultImage: "true"
        image.repository: bitnami/mariadb
        image.tag: 10.1.36-debian-9
        master.persistence.enabled: "false"
        master.persistence.size: 8Gi
        metrics.enabled: "false"
        metrics.image: prom/mysqld-exporter
        metrics.imageTag: v0.10.0
        replication.enabled: "true"
        service.type: NodePort
        slave.persistence.enabled: "false"
        slave.persistence.size: 8Gi
        slave.replicas: "2"
      name: test-mariadb
      targetNamespace: default
    when:
      branch:
        include:
        - aa
- name: mysql
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-nfs-provisioner
      version: 0.2.1
      name: nfs-aa
      targetNamespace: default
    when:
      branch:
        include:
        - aa
- name: publish
  steps:
  - publishCatalogConfig:
      path: ./mongodb/latest/
      catalogTemplate: mogoa
      version: foo-1.0.0+build5
      gitUrl: https://github.com/rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: aa
      gitEmail: aa
    envFrom:
    - sourceName: test-pipeline
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: test-pipeline
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
