global:
  systemDefaultRegistry: ""

systemUpgradeController:
  image:
    repository: rancher/system-upgrade-controller
    tag: v0.6.2

kubectl:
  image:
    repository: rancher/kubectl
    tag: v1.18.0
